"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Container from "@mui/material/Container";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,session
}: Readonly<{
  children: React.ReactNode;
  session:any;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container maxWidth="xl" className="px-0">
          <Header session={session} />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
