import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Container from "@mui/material/Container";

const inter = Inter({ subsets: ["latin"] });
interface layoutProps {
  children: ReactNode;
  session: any;
}


function RootLayout({ children, session }: layoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container maxWidth="xl" className="px-0">
          <Header session={session} />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
