name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t pradeep663299719/web-sphere:latest -f docker/Dockerfile .
          docker tag pradeep663299719/web-sphere:latest pradeep663299719/web-sphere:${{ github.sha }}
          docker push pradeep663299719/web-sphere:latest
          docker push pradeep663299719/web-sphere:${{ github.sha }}


      - name: Update Docker Compose file
        run: |
          sed "s|pradeep663299719/web-sphere:.*|pradeep663299719/web-sphere:${{ github.sha }}|" docker/docker-compose.yml
          echo "::set-output name=docker-compose-content::$(cat docker/docker-compose.yml)"
        id: update-docker-compose


      - name: Print updated Docker Compose file
        run: |
          echo "Copy and paste the following content into your local docker/docker-compose.yml file:"
          echo "${{ steps.update-docker-compose.outputs.docker-compose-content }}"